### ISSUE TITLE
Using Vitest, dom-testing-library enables fakeTimers when it wasn't enabled before

### ISSUE THREAD

**Issue by sheremet-va** [testing-library/dom-testing-library#1097]
- `@testing-library/dom` version: 7.31.2
- Testing Framework and version: Vitest 0.2.3
  
- DOM Environment: jsdom 19.0.0
  

### Problem description:

dom-testing-library enables fakeTimers when it wasn't enabled before

### Suggested solution:

I found that `useFakeTimers` called by helpers in `dist/helpers.js`:

```
Trace
    at FakeTimers.useFakeTimers (/Users/sheremet/local-git/work/lk3.sknt.ru/node_modules/vitest/dist/vi-7f0c5d26.js:5607:13)
    at VitestUtils.useFakeTimers (/Users/sheremet/local-git/work/lk3.sknt.ru/node_modules/vitest/dist/vi-7f0c5d26.js:5660:18)
    at runWithJestRealTimers (/Users/sheremet/local-git/work/lk3.sknt.ru/node_modules/@testing-library/vue/node_modules/@testing-library/dom/dist/helpers.js:52:10)
    at runWithRealTimers (/Users/sheremet/local-git/work/lk3.sknt.ru/node_modules/@testing-library/vue/node_modules/@testing-library/dom/dist/helpers.js:20:28)
    at Object.<anonymous> (/Users/sheremet/local-git/work/lk3.sknt.ru/node_modules/@testing-library/vue/node_modules/@testing-library/dom/dist/helpers.js:85:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

This happens because Vitest applies a getter on global, that returns `window`, so `global !== window` and `func !== globalObj[name]` check returns true and `dom-testing-library` assumes `useFakeTimers` was used.

**Comment by sheremet-va** [comment]
The issue may be in Vitest's approach. I will explore how we can fix it.

**Comment by eps1lon** [comment]
Thanks for the report.

We changed fake/real timer detection in 8.x so I would recommend upgrading first.

**Comment by eps1lon** [comment]
Closing due to lack of response. This was likely fixed in 8.x. If problems still occur in 8.x please provide a minimal repro.
