### ISSUE TITLE
Unable to find an input element by getByTestId or getByLabelText

### ISSUE THREAD

**Issue by kushalmahajan** [testing-library/dom-testing-library#374]
- @testing-library/react = "^9.2.0",
-  node - 12.10.0
- yarn - 1.17.3

### Relevant code or config:

```
const StyledInput = styled.input<
	Pick<Styles.InputProps, "error" | "disabled"> &
		Omit<Styles.InputProps, "onChange">
>`
export const Input: React.FC<
	Styles.InputProps &
		Omit<React.InputHTMLAttributes<HTMLInputElement>, "onChange">
> = ({
	type = "text",
	placeholder,
	label,
	error,
	helpText,
	block = false,
	disabled = false,
	onChange,
	onBlur,
	value,
	className,
	...rest
}: Styles.InputProps & React.InputHTMLAttributes<HTMLInputElement>) => {
	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		if (onChange) {
			onChange(e.target.value);
		}
	};
	return (
		<StyledWrapper block={block}>
			<StyledLabel error={error}>
				<label>{label}</label>
			</StyledLabel>
			<StyledInput
				type={type}
				placeholder={placeholder}
				error={error}
				disabled={disabled}
				onBlur={onBlur}
				onChange={handleChange}
				value={value}
				className={className}
				aria-labelledby="tm-input"
				{...rest}
			/>
			{error ? (
				<StyledError>
					<label>{error}</label>
				</StyledError>
			) : null}
			{helpText ? <StyledHelpText>{helpText}</StyledHelpText> : null}
		</StyledWrapper>
	);
};
```

 **input.stories.tsx** file

```
export const TestInput = () => {
	const [value, setValue] = React.useState("");
	const handleChange = (val: string) => {
		setValue(val);
	};
	return (
		<Input
			type="text"
			placeholder="Test input"
			value={value}
			onChange={handleChange}
		/>
	);
};
```
 **input.spec.js** file 

```
import React from "react";
import { fireEvent, render } from "@testing-library/react";
import { TestInput } from "./input.stories";

// afterEach(cleanUp);

describe("Input tests", () => {
	const { asFragment, getByLabelText } = render(<TestInput />);

	test("renders correcty", () => {
		expect(asFragment()).toMatchSnapshot();
	});

	test("Handles text change", () => {
		const input = getByLabelText("tm-input");
		fireEvent.change(input, { target: { value: "New value" } });
		expect(input.value).toBe("New value");
	});
});

```
```

### What you did:

yarn unit -u i.e.  "unit": "jest",

### What happened:

>  Input tests › Handles text change

    Unable to find a label with the text of: tm-input

    <body />

      13 | 
      14 |      test("Handles text change", () => {
    > 15 |              const input = getByLabelText("tm-input");
         |                            ^
      16 |              fireEvent.change(input, { target: { value: "New value" } });
      17 |              expect(input.value).toBe("New value");
      18 |      });

      at getElementError (node_modules/@testing-library/dom/dist/query-helpers.js:22:10)
      at getAllByLabelText (node_modules/@testing-library/dom/dist/queries/label-text.js:112:43)
      at node_modules/@testing-library/dom/dist/query-helpers.js:59:17
      at Object.getByLabelText (packages/web/src/components/input/input.spec.js:15:17)

**Comment by kushalmahajan** [comment]
I feel I need to file it in react-testing-library. Closing here
