### ISSUE TITLE
findByTestID throws 'TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.' with jest-environment-jsdom-fifteen

### ISSUE THREAD

**Issue by LaurensBosscher** [testing-library/dom-testing-library#419]
- `DOM Testing Library` version: 6.11.0
- `node` version: v12.11.1
- `npm` (or `yarn`) version: 1.21.1

**NB: I haven't been able to reproduce this bug in a small isolated environment** 

### Relevant code or config:

```js
    // Select all organizations
    const selectAllCheckbox = await findByTestId("select-all");
```

### What you did:

Before upgrading our packages this test worked w/h issues. After upgrading our packages this test started throwing the error beneath this and takes very long to run (b/c the MutationObserver doesn't work it seems to hit a timeout).

I've reverted the commit that upgraded the packages, this made the test work again.

I've upgraded the packages one by one to identify the issues. I can trigger the issue with the latest version of [jest-environment-jsdom-fifteen](https://github.com/ianschmitz/jest-environment-jsdom-fifteen). If I start from the working commit again and upgrade only jest-environment-jsdom-fifteen I get the same issue.

Dowgrading to the older version of jest-environment-jsdom-fifteen doesn't fix the issue so it might be a dependency of jest-environment-jsdom-fifteen that causes this error?

### What happened:

```js
    TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
        at convert (/home/laurens/dev/frontend/node_modules/jsdom/lib/jsdom/living/generated/Node.js:573:11)
        at MutationObserver.observe (/home/laurens/dev/frontend/node_modules/jsdom/lib/jsdom/living/generated/MutationObserver.js:43:16)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:34:52
        at runWithRealTimers (/home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/helpers.js:24:31)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:34:36
        at new Promise (<anonymous>)
        at waitForElement (/home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:25:10)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:70:54
        at /home/laurens/dev/frontend/node_modules/@testing-library/react/dist/pure.js:51:22
        at batchedUpdates$1 (/home/laurens/dev/frontend/node_modules/react-dom/cjs/react-dom.development.js:24386:12)

    TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
        at convert (/home/laurens/dev/frontend/node_modules/jsdom/lib/jsdom/living/generated/Node.js:573:11)
        at MutationObserver.observe (/home/laurens/dev/frontend/node_modules/jsdom/lib/jsdom/living/generated/MutationObserver.js:43:16)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:34:52
        at runWithRealTimers (/home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/helpers.js:24:31)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:34:36
        at new Promise (<anonymous>)
        at waitForElement (/home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:25:10)
        at /home/laurens/dev/frontend/node_modules/@testing-library/dom/dist/wait-for-element.js:70:54
        at /home/laurens/dev/frontend/node_modules/@testing-library/react/dist/pure.js:51:22
        at batchedUpdates$1 (/home/laurens/dev/frontend/node_modules/react-dom/cjs/react-dom.development.js:24386:12)
```

If I place a console.log at "/home/laurens/dev/frontend/node_modules/jsdom/lib/jsdom/living/generated/MutationObserver.js:42" I get:

```js
Document {
  location: [Getter/Setter],
  [Symbol(DOM SymbolTree)]: SymbolTreeNode {
    parent: null,
    previousSibling: null,
    nextSibling: null,
    firstChild: null,
    lastChild: null,
    childrenVersion: 0,
    childIndexCachedUpTo: null,
    cachedIndex: -1,
    cachedIndexVersion: NaN
  }
}
```

If I place a console.log at " ../node_modules/@testing-library/dom/dist/wait-for-element.js:23" I get

```js
  console.log ../node_modules/@testing-library/dom/dist/wait-for-element.js:23
    container Document { location: [Getter/Setter] }

  console.log ../node_modules/@testing-library/dom/dist/wait-for-element.js:23
    container Document {
      location: [Getter/Setter],
      [Symbol(DOM SymbolTree)]: SymbolTreeNode {
        parent: null,
        previousSibling: null,
        nextSibling: null,
        firstChild: null,
        lastChild: null,
        childrenVersion: 0,
        childIndexCachedUpTo: null,
        cachedIndex: -1,
        cachedIndexVersion: NaN
      }
    }
```

### Reproduction:

Not yet

### Problem description:

Jest 25 will use JSDom fifteen as the default. This issues _might_ indicate incompatibility issues. This _might_ be the same issue as #348 (just with a different trace because JSDom fifteen includes support for MutationObservers instead of using the shim.

**Comment by LaurensBosscher** [comment]
After a lot of debugging it seems that [React-Focus-Lock](https://github.com/theKashey/react-focus-lock) was the issue and not dom-testing-library. This issue can be closed.
