### ISSUE TITLE
Docs Are incorrect for Cypress -- bylabeltext

### ISSUE THREAD

**Issue by lmon** [testing-library/dom-testing-library#455]
- `DOM Testing Library` version: 5.3.0
- `node` version: v12.6.0
- `npm` (or `yarn`) version: 1.17.3

### Relevant code or config:

```js
// this recommended code in the docs (https://testing-library.com/docs/dom-testing-library/api-queries#bylabeltext) is inconsistent with @testing-library/cypress syntax
cy.getByLabelText('username').should('exist');
```
### What you did:

Ran the following command `cy.getByLabelText('username').should('exist');`

### What happened:

In console this error was displayed
```
cypress_runner.js:174890 Command:  getByLabelText
cypress_runner.js:174890 Error: Error: You used 'getByLabelText' which has been removed from Cypress Testing Library because it does not make sense in this context. Please use 'findByLabelText' instead.
    at Context.command (https://local.food52staging.com:3443/__cypress/tests?p=test/cypress/support/index.js-623:950:13)
From previous event:
    at runCommand (https://local.food52staging.com:3443/__cypress/runner/cypress_runner.js:96883:14)
    at next (https://local.food52staging.com:3443/__cypress/runner/cypress_runner.js:97026:14)
    at https://local.food52staging.com:3443/__cypress/runner/cypress_runner.js:97054:16
```

### Problem description:

Failure

### Suggested solution:

Following the recommendation in the error is successful:
`cy.findByLabelText('username').should('exist')`

All of the Cypress -specific documentation should be updated:
<img width="798" alt="Screen Shot 2020-02-28 at 11 38 49 AM" src="https://user-images.githubusercontent.com/1000546/75567096-f2f6ca00-5a1e-11ea-9707-47969ee4e8dd.png">

to reflect the current recommended syntax. 

I am happy to do this if I can be pointed to the location of the documentation repo.
Thank you!

**Comment by afontcu** [comment]
Hi! Nice catch :) we should definitely replace `cy.getByXXX` with `cy.findByXXX` everywhere!

Docs are here: https://github.com/testing-library/testing-library-docs
