### ISSUE TITLE
waitFor behavior has changed

### ISSUE THREAD

**Issue by pustovalov** [testing-library/dom-testing-library#503]
### Before

- `DOM Testing Library` version: 6.16.0

- `node` version: 13.11.0
- `npm` (or `yarn`) version: 1.22.4

### Relevant code or config:

```
 PASS  app/javascript/__tests__/some_test.test.js
  AbTestsSplitTestsEntries
    localization for Advocate social sharing
      ✓ should render preview iframe (252ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.278s
✨  Done in 4.23s.
```

### After update

- `DOM Testing Library` version: 7.1.1

- `node` version: 13.11.0
- `npm` (or `yarn`) version: 1.22.4

### Relevant code or config:

```
AbTestsSplitTestsEntries › localization for Advocate social sharing › should render preview iframe

    expect(received).toContain(expected) // indexOf

    Expected substring: "Specify Variants to Test"
    Received string:    "Back to All A/B testsShow All A/B TestsCreate a New Content A/B TestLearn More"

      126 |       await waitFor(() => {container.querySelector('.ac-ab-tests-layout')}, {timeout: 8000})
      127 |
    > 128 |       expect(container.querySelector('.ac-ab-tests-layout').textContent).toContain(
          |                                                                          ^
      129 |         'Specify Variants to Test',
      130 |       )
      131 |

      at _callee$ (app/javascript/__tests__/some_test.testjs:128:74)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:145:13

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.111s
```

### Reproduce
https://codesandbox.io/s/react-testing-library-demo-73m3x

### What you did:

I tried to add a timeout for `waitFor` but it didn't help:
```
await waitFor(() => {container.querySelector('.ac-ab-tests-layout')}, {timeout: 8000})
```

added `console.log` inside component which `waitFor` waiting, and I can see that `console.log` in log of spec

### Problem description:

Looks like `waitFor` changed it behavior, and no longer waiting an element to appear in the document

**Comment by pustovalov** [comment]
If use `getByTestId` I got this error:

```
Found multiple elements by: [data-testid="ac-second"]

(If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).
```

Reproduce
https://codesandbox.io/s/react-testing-library-demo-sbqw1

**Comment by pustovalov** [comment]
Found a solution:
```
test("Render second component", async done => {
  const { findByTestId } = render(<FirstComponent />);

  const secondComponent = await findByTestId("ac-second");

  expect(secondComponent.textContent).toContain("second");
  done();
});
```
https://codesandbox.io/s/react-testing-library-demo-glfu5

**Comment by timdeschryver** [comment]
`waitFor` needs an expectation to "wait", otherwise it will just wait a tick and go through with the rest of the test.

From the docs:
> When in need to wait for any period of time you can use waitFor, to wait for your expectations to pass

So the following should work

```js
  await waitFor(() => {
    expect(container.querySelector(".ac-second").textContent).toContain("second");
  });
```

**Comment by pustovalov** [comment]
Thx, you are right
https://codesandbox.io/s/react-testing-library-demo-heff7

closing the issue
