### ISSUE TITLE
All async specs failed if one spec was failed

### ISSUE THREAD

**Issue by pustovalov** [testing-library/dom-testing-library#560]
- `@testing-library/dom` version: 7.5.1
- `@testing-library/react` version: 10.0.4
- `node`: 12.16.3
- Testing Framework and version:
  
- DOM Environment:
- `jest`: 24.9.0 (same on 25.5.4)
  
```
react-scripts#jest-environment-jsdom-fourteen
jest-environment-jsdom#jsdom@11.12.0
```

### Relevant code or config:

```js

describe(`main`, () => {
  test('only this spec should be failed', async done => {
    const { findByTestId } = render(<App />)
    const test = await findByTestId('random-test-id')
    expect(test).toBeInTheDocument()

    done()
  })

  test('should be success', async done => {
    const { findByTestId } = render(<App />)
    const test = await findByTestId('learn-button')

    expect(test).toBeInTheDocument()
    done()
  })
})
```

### Expected result:

```
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
```

### What happened:

```
main
    ✕ only this spec should be failed (1023ms)
    ✕ should be success (1004ms)

  ● main › only this spec should be failed

    TestingLibraryElementError: Unable to find an element by: [data-testid="random-test-id"]

    <body>
      <div>
        <div
          class="App"
        >
          <header
            class="App-header"
          >
            <img
              alt="logo"
              class="App-logo"
              src="logo.svg"
            />
            <p>
              Edit
              <code>
                src/App.js
              </code>
               and save to reload.
            </p>
            <a
              class="App-link"
              data-testid="learn-button"
              href="https://reactjs.org"
              rel="noopener noreferrer"
              target="_blank"
            >
              Learn React
            </a>
          </header>
        </div>
      </div>
    </body>Error: Unable to find an element by: [data-testid="random-test-id"]

    <body>
      <div>
        <div
          class="App"
        >
          <header
            class="App-header"
          >
            <img
              alt="logo"
              class="App-logo"
              src="logo.svg"
            />
            <p>
              Edit
              <code>
                src/App.js
              </code>
               and save to reload.
            </p>
            <a
              class="App-link"
              data-testid="learn-button"
              href="https://reactjs.org"
              rel="noopener noreferrer"
              target="_blank"
            >
              Learn React
            </a>
          </header>
        </div>
      </div>
    </body>

       6 |   test('only this spec should be failed', async done => {
       7 |     const { findByTestId } = render(<App />)
    >  8 |     const test = await findByTestId('random-test-id')
         |                        ^
       9 |     expect(test).toBeInTheDocument()
      10 |
      11 |     done()

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:94:27)
      at findByTestId (node_modules/@testing-library/dom/dist/query-helpers.js:86:77)
      at Object.<anonymous> (src/App.test.js:8:24)

  ● main › should be success

    TestingLibraryElementError: Unable to find an element by: [data-testid="learn-button"]

    <body />Error: Unable to find an element by: [data-testid="learn-button"]

    <body />

      14 |   test('should be success', async done => {
      15 |     const { findByTestId } = render(<App />)
    > 16 |     const test = await findByTestId('learn-button')
         |                        ^
      17 |
      18 |     expect(test).toBeInTheDocument()
      19 |     done()

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:94:27)
      at findByTestId (node_modules/@testing-library/dom/dist/query-helpers.js:86:77)
      at Object.<anonymous> (src/App.test.js:16:24)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        4.678s
```

### Reproduction:

https://github.com/pustovalov/react-testing-library-repro/blob/master/src/App.test.js#L5

tried these ways:

- remove done callback
- use `waitFor`

but the behavior is the same

### Problem description:

with current behavior, it's hard to determine which test is actually broken

**Comment by pustovalov** [comment]
Solution:
```
describe(`main`, () => {
  test('only this spec should be failed', async() => {
    const { findByTestId } = render(<App />)
    const test = await findByTestId('random-test-id')

    expect(test).toBeInTheDocument()
  })

  test('should be success', async() => {
    const { findByTestId } = render(<App />)
    const test = await findByTestId('learn-button')

    expect(test).toBeInTheDocument()
  })
})
```
https://spectrum.chat/testing-library/general/all-async-specs-failed-if-one-spec-was-failed~db6ffaa4-6d40-4859-925b-f90cba0d2e05
