### ISSUE TITLE
TypeError: performance.getEntriesByType is not a function while executing the test

### ISSUE THREAD

**Issue by slim-hmidi** [testing-library/dom-testing-library#895]
- `@testing-library/dom` version: 7.26.7
- Testing Framework and version: @jest/core 26.6.3
  
- DOM Environment: jsdom 16.4.0
  

### Relevant code or config:

```tsx
import React, {useCallback, useEffect} from 'react';
import {Redirect, RouteComponentProps, Route } from 'react-router-dom';


interface Props {
  component: React.FC<any>;
  render?: (props: RouteComponentProps<any>) => React.ReactNode;
  path: string;
  role: string;
  redirectionPath?: string;
}

const RefreshRoute = ({
  component: Component,
  redirectionPath,
  ...rest
}: Props): JSX.Element => {
  redirectionPath = redirectionPath ?? '/';
  const perf = performance.getEntriesByType('navigation')[0].toJSON();
  const reloadType = perf.type !== 'reload';

  const handler = useCallback((e) => {
    e.preventDefault();
    e.returnValue = '';
    return true;
  }, []);

  useEffect(() => {
    window.onbeforeunload = handler;

    return () => {
      window.onbeforeunload = handler;
    };
  }, [handler]);
  return (
    <>
      {reloadType ? (
        <Route component={Component} {...rest} />
      ) : (
        <Redirect to={redirectionPath} />
      )}
    </>
  );
};
export default RefreshRoute;
```

RefreshRoute.test.tsx:
```
import React from 'react';
import {render, screen} from 'test/CustomRender';
import {MemoryRouter} from 'react-router-dom';
import App from '../App';

describe('RefreshRoute', () => {
  test('Should render the component successfully in the first render', () => {
    render(
      <MemoryRouter
        initialEntries={['/', '/refs', '/refs/create', '/lib']}
        initialIndex={2}
      >
        <App />
      </MemoryRouter>,
      {},
    );

    expect(screen.getByLabelText(/creation/)).toBeInTheDocument();
  });
});
````

### What you did:

When I run the test to check a given component rendered correctly in th document.

### What happened:

I got this error while executing the tests:
```
 TypeError: performance.getEntriesByType is not a function

      17 | }: Props): JSX.Element => {
      18 |   redirectionPath = redirectionPath ?? '/';
    > 19 |   const perf = performance.getEntriesByType('navigation')[0].toJSON();
         |                            ^
      20 |   const reloadType = perf.type !== 'reload';
      21 | 
      22 |   const handler = useCallback((e) => {

      at RefreshRoute (src/app/routes/RefreshRoute.tsx:19:28)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at render (src/test/CustomRender.tsx:47:10)
      at Object.<anonymous> (src/app/routes/RefreshRoute.test.tsx:8:5)
```

### Problem description:

The test fails due to the call of `performance` inside the RefreshRoute.

### Suggested solution:

The perfomance should be took into consideration with jsdom.

**Comment by eps1lon** [comment]
Thanks for the report.

This is not something `@testing-library/dom` can change. It looks like `jsdom` does not implement `performance.getEntriesByType`. Please open a [new issue on the `jsdom` repository](https://github.com/jsdom/jsdom/issues/new/choose) instead.

**Comment by slim-hmidi** [comment]
@eps1lon thanks a lot for your quick answer, I hesitated before writing this issue if it's related to `@testing-library` or not. I'll open an issue in the jsdom repo.
thanks for your time.

**Comment by eps1lon** [comment]
@slim-hmidi Thanks for the consideration! I'm closing this unless JSDOM kicks this back to us. Please link the opened JSDOM issue once you've created it so that others may be directed in the proper direction as well.

**Comment by slim-hmidi** [comment]
https://github.com/jsdom/jsdom/issues/3122
