### ISSUE TITLE
Using afterEach to clear timer leads to [TypeError: Cannot read property 'parentElement' of null]

### ISSUE THREAD

**Issue by osaid-r** [testing-library/dom-testing-library#915]
- `@testing-library/dom` version: 7.29.4
- Testing Framework and version: jest 24.9.0
  
- DOM Environment: jsdom 14.1.0
  

### Relevant code or config:

```js
const Component = () => {
   useEffect(() => {
    setTimeout(fn, 1000);
  });
}

// in test
beforeEach(() => {
  jest.useFakeTimers();
});

afterEach(() => {
  jest.runOnlyPendingTimers();
  jest.useRealTimers();
});

// multiple test cases
```

### What you did:
Using just `cleanup` works, but it's not ideal since it leads to some unwanted issues. Using the method mentioned in the documentation (i.e using `jest.useRealTimers()`) leads to `Error: Uncaught [TypeError: Cannot read property 'parentElement' of null]`.

In any case just having one test (i.e never running `afterEach`) leads to the test passing. 

### What happened:
```
Error: Uncaught [TypeError: Cannot read property 'parentElement' of null]
        at reportException (/Users/onasir/workspace/incDash_trunk/incDash/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at Timeout.callback [as _onTimeout] (/Users/onasir/workspace/incDash_trunk/incDash/node_modules/jsdom/lib/jsdom/browser/Window.js:673:7)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7) TypeError: Cannot read property 'parentElement' of null
```

### Reproduction:
Will add a reproducible repo ASAP

### Problem description:
It should work without any issues.

**Comment by osaid-r** [comment]
I believe it has to do with some library I'm using, closing it for now, will reopen if it seems necessary.
