### ISSUE TITLE
cannot test with react-hook-form and material ui

### ISSUE THREAD

**Issue by asaadawey** [testing-library/dom-testing-library#960]
- `@testing-library/dom` version: 5.12.0
- Testing Framework and version:
- Jest :26.0
- React 17
- DOM Environment: React

### Relevant code or config:

```form.test.tsx
    it("should display this field is required error when submit is pressed", async () => {
      //Construct items to pass it then to form
    const items: FormItemsProps[] = [
      { name: "test", label: "test", type: "input" },
      { name: "test2", label: "test2", type: "input" },
    ];
    await act(async () => {
      render(
        <div>
          <Form
            id="testform"
            items={items}
            schema={Joi.object({
              test: Joi.string().required(),
              test2: Joi.string().required(),
            })}
            onSubmit={(v) => {}}
            orientation={"horizental"}
          />
          <button form="testform" type="submit">
            testsubmit
          </button>
        </div>
      );
      await fireEvent.submit(screen.getByText("testsubmit"));

      await waitFor(() =>
        expect(screen.getAllByText(/required/).length).toBe(2)
      );
    });
    });
```

### What you did:

I have a form component . Which accepts 

id - the form id
items - contains an array of items to render
schema - accepts joi validation schema to validate

the form component uses react-hook-form library version 7.3.6 and material ui 4.11.4

i need to test this form component . i need to ensure if i have presses the submit button . i will receive two error messages that contains 'xxxx is required'

### What happened:

The test fails with this error

```
    Unable to find an element with the text: /required/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for 
your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div
            class="makeStyles-root-1"
          >
            <form
              id="testform"
            >
              <section
                class="MuiGrid-root makeStyles-root-1 MuiGrid-container"
              >
                <div
                  class="MuiGrid-root makeStyles-paper-2 MuiGrid-item MuiGrid-grid-xs-4"
                >
                  <div
                    class="makeStyles-wrapper-5"
                  >
                    <div
                      class="MuiFormControl-root MuiTextField-root MuiFormControl-fullWidth"
                    >
                      <label
                        class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-outlined"       
                        data-shrink="true"
                      >
                        test
                      </label>
                      <div
                        class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedStart MuiOutlinedInput-adornedStart MuiInputBase-adornedEnd MuiOutlinedInput-adornedEnd"
                      >
                        <div
                          class="MuiInputAdornment-root MuiInputAdornment-positionStart"
                        >
                          <p
                            class="MuiTypography-root MuiTypography-body1 MuiTypography-colorTextSecondary"
                          />
                        </div>
                        <input
                          aria-invalid="false"
                          class="MuiInputBase-input MuiOutlinedInput-input makeStyles-input-4 MuiInputBase-inputAdornedStart MuiOutlinedInput-inputAdornedStart MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd"
                          name="test"
                          type="input"
                          value=""
                        />
                        <div
                          class="MuiInputAdornment-root MuiInputAdornment-positionEnd"
                        >
                          <p
                            class="MuiTypography-root MuiTypography-body1 MuiTypography-colorTextSecondary"
                          />
                        </div>
                        <fieldset
                          aria-hidden="true"
                          class="PrivateNotchedOutline-root-6 MuiOutlinedInput-notchedOutline"
                        >
                          <legend
                            class="PrivateNotchedOutline-legendLabelled-8 PrivateNotchedOutline-legendNotched-9"
                          >
                            <span>
                              test
                            </span>
                          </legend>
                        </fieldset>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="MuiGrid-root makeStyles-paper-2 MuiGrid-item MuiGrid-grid-xs-4"
                >
                  <div
                    class="makeStyles-wrapper-5"
                  >
                    <div
                      class="MuiFormControl-root MuiTextField-root MuiFormControl-fullWidth"
                    >
                      <label
                        class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-outlined"       
                        data-shrink="true"
                      >
                        test2
                      </label>
                      <div
                        class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedStart MuiOutlinedInput-adornedStart MuiInputBase-adornedEnd MuiOutlinedInput-adornedEnd"
                      >
                        <div
                          class="MuiInputAdornment-root MuiInputAdornment-positionStart"
                        >
                          <p
                            class="MuiTypography-root MuiTypography-body1 MuiTypography-colorTextSecondary"
                          />
                        </div>
                        <input
                          aria-invalid="false"
                          class="MuiInputBase-input MuiOutlinedInput-input makeStyles-input-4 MuiInputBase-inputAdornedStart MuiOutlinedInput-inputAdornedStart MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd"
                          name="test2"
                          type="input"
                          value=""
                        />
                        <div
                          class="MuiInputAdornment-root MuiInputAdornment-positionEnd"
                        >
                          <p
                            class="MuiTypography-root MuiTypography-body1 MuiTypography-colorTextSecondary"
                          />
                        </div>
                        <fieldset
                          aria-hidden="true"
                          class="PrivateNotchedOutline-root-6 MuiOutlinedInput-notchedOutline"
                        >
                          <legend
                            class="PrivateNotchedOutline-legendLabelled-8 PrivateNotchedOutline-legendNotched-9"
                          >
                            <span>
                              test2
                            </span>
                          </legend>
                        </fieldset>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </form>
          </div>
          <button
            form="testform"
            type="submit"
          >
            testsubmit
          </button>
        </div>
      </div>
    </body>

      44 |       await fireEvent.submit(screen.getByText("testsubmit"));
      45 |
    > 46 |       await waitFor(() =>
         |             ^
      47 |         expect(screen.getAllByText(/required/).length).toBe(2)
      48 |       );
      49 |     });

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at src/components/common/form/form.test.tsx:46:13
```

### Problem description:

It's showing an error message . And the test fails

### Suggested solution:

i have tried using 'act()' , using query selectors to access the button
i have followed the testing guide mentioned in the react-hook-form testing . no chance

**Comment by eps1lon** [comment]
Firing a submit event does not go through form validation. What you probably want is [`form.requestSubmit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit).

**Comment by asaadawey** [comment]
@eps1lon 

edited my code to be 

```
  it("should display required error when value is invalid", async () => {
    await act(async () => {
      const { container } = render(
        <ApolloProvider client={client}>
          <Login name="" />
        </ApolloProvider>
      );
      (
        container.querySelector("form[id=login-form]") as HTMLFormElement
      ).requestSubmit();

      const a = await screen.findAllByText(/required/);
      console.log(a);
    });
  });
```

still facing the same problem

**Comment by eps1lon** [comment]
Could you add a cloneable repro that we can try out?

**Comment by eps1lon** [comment]
Closing since no response was given in over 3 months.
