### ISSUE TITLE
getByRole unable to find button elements

### ISSUE THREAD

**Issue by gdostie** [testing-library/dom-testing-library#973]
- `@testing-library/react` version: 11.2.7
- `@testing-library/dom` the one shipped with `@testing-library/react` (^7.28.1)
- Testing Framework and version: Jest 27.0.4
  
- DOM Environment: jsdom, not sure what version
  

### Relevant code or config:

```js
it('renders an edit button', () => {
  render(<button>Edit</button>);
  expect(screen.getByRole("button", { name: /edit/i }));
});
```

### What you did:

Ran the test above.

### What happened:

```
Unable to find an accessible element with the role "button" and name `/edit/i`

There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

<body>
  <div>
    <button>
      Edit
    </button>
  </div>
</body>

TestingLibraryElementError: Unable to find an accessible element with the role "button" and name `/edit/i`

There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

<body>
  <div>
    <button>
      Edit
    </button>
  </div>
</body>
    at Object.getElementError (https://o8wdc.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:775:17)
    at eval (https://o8wdc.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1466:25)
    at eval (https://o8wdc.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1446:24)
    at eval (https://o8wdc.csb.app/node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1485:25)
    at Object.eval (https://o8wdc.csb.app/src/__tests__/Repro.js:15:26)
    at https://codesandbox.io/static/js/2.9e4369f2f.chunk.js:1:336449
    at new Promise (<anonymous>)
    at t.callAsyncFn (https://codesandbox.io/static/js/2.9e4369f2f.chunk.js:1:336108)
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:6524
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:6791
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:5456
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:5814
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:4116
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:4778
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:4366
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at Generator.forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:4778
    at https://codesandbox.io/static/js/7.3958676be.chunk.js:1:3116
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
```

### Reproduction:

[See this sandbox](https://codesandbox.io/s/react-testing-library-demo-forked-hnijj?file=/src/__tests__/hello.js)

### Problem description:

The `button` tag is supposed to have the built-in `button` role.

**Comment by eps1lon** [comment]
Thanks for the feedback. 

This is a bug with codesandbox. If you download the codesandbox and run the tests locally, all tests pass. Please [create a bug report in the codesandbox repository](https://github.com/codesandbox/codesandbox-client/issues/new?assignees=&labels=&template=BUG.md)

**Comment by gdostie** [comment]
If anyone experiences the same issue, you can follow the bug [here](https://github.com/codesandbox/codesandbox-client/issues/5887).
